name: flutter_commons
description: A package that contains classes, that are not released as a public library but still re-used across different projects.
version: 1.0.0
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  mockito: ^4.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: